site_name: PDF Censor
repo_url: https://github.com/pho-souza/pdf-censor
repo_name: pho-souza/pdf-censor
edit_uri: tree/main/docs


theme:
  name: material
  language: pt-BR
  logo: /assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css


plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [pdf_censor]